### ISSUE TITLE
Mod fails to load. Error during load_registries event

### ISSUE THREAD

**Issue by ZephaniahNoah** [progwml6/ironshulkerboxes#2]
![Screenshot_2019-08-30_22-47-03](https://user-images.githubusercontent.com/14168013/64061551-20e67900-cb78-11e9-94f3-bd28ed2d9156.png)
Forge version 25.0.219
```
[30Aug2019 22:42:24.821] [Client thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: field_176387_N
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class com.progwml6.ironshulkerbox.common.tileentity.IronShulkerBoxEntityType$Registration onTileEntityRegistry(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		2: ASM: class com.progwml6.ironshulkerbox.common.core.IronShulkerBoxItems$Registration registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		3: ASM: class com.progwml6.ironshulkerbox.common.core.IronShulkerBoxBlocks$Registration registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V
		4: ASM: class com.progwml6.ironshulkerbox.common.core.IronShulkerBoxBlocks$Registration registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.NoSuchFieldError: field_176387_N
	at com.progwml6.ironshulkerbox.common.blocks.BlockShulkerBox.<clinit>(BlockShulkerBox.java:59)
	at com.progwml6.ironshulkerbox.common.core.IronShulkerBoxBlocks$Registration.registerBlocks(IronShulkerBoxBlocks.java:529)
	at net.minecraftforge.eventbus.ASMEventHandler_2_Registration_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:254)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:105)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$4(ModList.java:111)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:111)
	at net.minecraftforge.fml.ModList.lambda$static$0(ModList.java:82)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:70)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:153)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:891)
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:141)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:63)
	at net.minecraft.client.Minecraft.init(Minecraft.java:412)
	at net.minecraft.client.Minecraft.run(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:98)
```

**Comment by ZephaniahNoah** [comment]
Same issue in 1.14
EDIT: Forge 28.0.75

**Comment by ZephaniahNoah** [comment]
I found out that this is actually a problem with Forge. My bad.
EDIT: To clarify, it happens when you try to load a mod from the BuildPath / Referenced Libraries.
EDIT 2: It also happens when loading from the /run/mods folder. It seems Forge just doesn't allow loading other mods in a dev environment right now.
